groups:
- jobs:
  - build-docs
  - test-ubuntu-xenial
  - create-beta
  - publish
  name: all
- jobs:
  - bump-major
  - bump-minor
  - bump-patch
  name: ci-state
jobs:
- name: build-docs
  serial: true
  plan:
  - aggregate:
    - get: repo
      trigger: true
    - get: artifacts
      resource: repo-artifacts
      trigger: true
    - get: hugo-site
      trigger: true
  - task: build-docs
    file: repo/ci/tasks/build-docs.yml
  - put: repo-gh-pages
    params:
      repository: public
      force: true
- name: test-ubuntu-xenial
  serial: true
  serial_groups:
  - highload
  plan:
  - get: repo
    trigger: true
  - get: stemcell
    resource: ubuntu-xenial-stemcell
  - task: test
    file: repo/ci/tasks/test-deploy.yml
    privileged: true
- name: create-beta
  plan:
  - get: repo
    trigger: true
    passed:
    - test-ubuntu-xenial
  - task: create-beta
    file: repo/ci/tasks/create-dev-release-tarball.yml
  - put: beta-bosh-release-tarball
    params:
      files:
      - release/*.tgz
      version: release/version
    get_params:
      skip_download: true
- name: publish
  serial_groups:
  - version
  plan:
  - get: repo
    passed:
    - create-beta
  - get: beta-bosh-release-tarball
    passed:
    - create-beta
  - get: version
  - do:
    - put: bosh-release
      params:
        tarball: beta-bosh-release-tarball/*.tgz
        version: version/version
    - put: bosh-release-tarball
      params:
        files:
        - bosh-release/*.tgz
        version: bosh-release/version
    - task: build-release-metadata
      file: repo/ci/tasks/build-release-metadata.yml
    - put: github-release
      params:
        name: release-metadata/name
        tag: release-metadata/tag
        body: release-metadata/notes.md
        globs:
        - bosh-release-tarball/*.tgz
    ensure:
      put: version
      params:
        bump: patch
- name: bump-major
  serial_groups:
  - version
  plan:
  - put: version
    params:
      bump: major
- name: bump-minor
  serial_groups:
  - version
  plan:
  - put: version
    params:
      bump: minor
- name: bump-patch
  serial_groups:
  - version
  plan:
  - put: version
    params:
      bump: patch
resources:
- name: repo
  type: git
  source: &repo
    uri: git@github.com:dpb587/caddy-bosh-release.git
    branch: master
    private_key: ((ci_deploy_ssh_key))
- name: "repo-artifacts"
  type: "git"
  source:
    uri: git@github.com:dpb587/caddy-bosh-release.git
    branch: artifacts
    private_key: ((ci_deploy_ssh_key))
- name: "repo-gh-pages"
  type: "git"
  source:
    uri: git@github.com:dpb587/caddy-bosh-release.git
    branch: gh-pages
    private_key: ((ci_deploy_ssh_key))
- name: version
  type: semver
  source:
    <<: *repo
    driver: git
    branch: ci-state
    file: version/master
- name: bosh-release
  type: bosh-release
  source:
    <<: *repo
    private_config:
      blobstore:
        options:
          access_key_id: ((ci_access_key))
          secret_access_key: ((ci_secret_key))
- name: github-release
  type: github-release
  source:
    owner: dpb587
    repository: caddy-bosh-release
    access_token: ((github_access_token))
- name: beta-bosh-release-tarball
  type: metalink-repository
  source:
    << : *release_artifacts
    uri: git+ssh://git@github.com:dpb587/caddy-bosh-release.git//release/beta#artifacts
- name: bosh-release-tarball
  type: metalink-repository
  source:
    << : *release_artifacts
    uri: git+ssh://git@github.com:dpb587/caddy-bosh-release.git//release/stable#artifacts
- name: ubuntu-xenial-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-xenial-go_agent
- name: "hugo-site"
  type: "git"
  source:
    uri: https://github.com/dpb587/hugo-balmy-site.git
- name: slack-alert
  type: slack-notification
  source:
    url: ((ci_slack_hook_url))
resource_types:
- name: bosh-release
  type: docker-image
  source:
    repository: dpb587/bosh-release-resource
- name: dynamic-metalink
  type: docker-image
  source:
    repository: dpb587/dynamic-metalink-resource
- name: metalink-repository
  type: docker-image
  source:
    repository: dpb587/metalink-repository-resource
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
shared:
  release_artifacts: &release_artifacts
    mirror_files:
    - destination: s3://s3-external-1.amazonaws.com/dpb587-caddy-bosh-release-us-east-1/artifacts/release/{{.SHA1}}
      env:
        AWS_ACCESS_KEY_ID: ((ci_access_key))
        AWS_SECRET_ACCESS_KEY: ((ci_secret_key))
    options:
      private_key: ((ci_deploy_ssh_key))
bosh_release_blobs_upgrader:
  track_files:
  - .resource/metalink.meta4
  resource_defaults:
    check_every: 6h
  serial_groups:
  - serial
  before_upload:
    task: test
    file: repo/ci/tasks/test-deploy.yml
    privileged: true
  after_upload:
    put: repo
    params:
      repository: repo
      rebase: true
  on_failure:
    put: slack-alert
    params:
      text: Failed to upgrade ((blob)) to v$TEXT_FILE_CONTENT.
      text_file: blob/.resource/version
      attachments:
      - author_icon: https://github.com/concourse.png
        author_name: upgrader pipeline
        author_link: https://github.com/dpb587/caddy-bosh-release/blob/master/ci/pipelines/main.yml
        title: $BUILD_JOB_NAME/$BUILD_NAME
        title_link: $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        color: danger
  on_success:
    put: slack-alert
    params:
      text: Successfully upgraded ((blob)) to v$TEXT_FILE_CONTENT.
      text_file: blob/.resource/version
      attachments:
      - author_icon: https://github.com/concourse.png
        author_name: upgrader pipeline
        author_link: https://github.com/dpb587/caddy-bosh-release/blob/master/ci/pipelines/main.yml
        title: $BUILD_JOB_NAME/$BUILD_NAME
        title_link: $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        color: good
