---
- path: /instance_groups/name=caddy/jobs/name=caddy/properties/caddyfile
  type: replace
  value: |
    ((external_host)) {
      gzip
      proxy / localhost:8080 {
        transparent
        websocket
      }
    }
